# Generated by Django 5.1 on 2024-09-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_laptop_remove_product_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='brand',
            field=models.CharField(default='Intel', max_length=250),
        ),
    ]
