# Generated by Django 5.1 on 2024-09-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_slider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.charfield>', max_length=150, unique=True),
        ),
    ]
