# Generated by Django 5.1 on 2024-09-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_slider_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slug',
        ),
    ]
