# Generated by Django 5.1 on 2024-09-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_slider_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default=None, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
