# Generated by Django 5.1 on 2024-09-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_slider_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('brand', models.CharField(default='', max_length=250)),
                ('form_factor', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=100)),
                ('cooling_support', models.BooleanField(default=True)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='CPUCooler',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('brand', models.CharField(default='', max_length=250)),
                ('fan_speed', models.CharField(max_length=250)),
                ('cooler_type', models.CharField(max_length=250)),
                ('rgb', models.BooleanField(default=False)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('brand', models.CharField(default='', max_length=250)),
                ('gpu_chipset', models.CharField(max_length=250)),
                ('memory_size', models.CharField(max_length=250)),
                ('memory_type', models.CharField(max_length=250)),
                ('clock_speed', models.CharField(max_length=250)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='HardDisk',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('brand', models.CharField(default='', max_length=250)),
                ('capacity', models.CharField(max_length=250)),
                ('form_factor', models.CharField(max_length=250)),
                ('rpm', models.IntegerField()),
                ('cache_size', models.CharField(max_length=250)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Keyboards',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('connection_type', models.CharField(max_length=250)),
                ('key_switch_type', models.CharField(max_length=250)),
                ('rgb', models.BooleanField(default=False)),
                ('layout', models.CharField(max_length=250)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('brand', models.CharField(default='', max_length=250)),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('resolution', models.CharField(max_length=250)),
                ('refresh_rate', models.CharField(max_length=250)),
                ('panel_type', models.CharField(max_length=250)),
                ('response_time', models.CharField(max_length=250)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('brand', models.CharField(default='', max_length=250)),
                ('chipset', models.CharField(max_length=250)),
                ('socket_type', models.CharField(max_length=250)),
                ('form_factor', models.CharField(max_length=250)),
                ('max_memory', models.CharField(max_length=250)),
                ('memory_type', models.CharField(max_length=250)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('connection_type', models.CharField(max_length=250)),
                ('dpi', models.CharField(max_length=250)),
                ('rgb', models.BooleanField(default=False)),
                ('number_of_buttons', models.IntegerField()),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('brand', models.CharField(default='', max_length=250)),
                ('max_wattage', models.CharField(max_length=250)),
                ('efficiency_rating', models.CharField(max_length=250)),
                ('modular', models.BooleanField(default=False)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Processors',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('brand', models.CharField(default='', max_length=250)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('base_clock', models.CharField(max_length=250)),
                ('boost_clock', models.CharField(max_length=250)),
                ('socket_type', models.CharField(max_length=250)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('capacity', models.CharField(max_length=250)),
                ('memory_type', models.CharField(max_length=250)),
                ('speed', models.CharField(max_length=250)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('capacity', models.CharField(max_length=250)),
                ('form_factor', models.CharField(max_length=250)),
                ('read_speed', models.CharField(max_length=250)),
                ('write_speed', models.CharField(max_length=250)),
                ('wattage', models.IntegerField()),
            ],
            bases=('product.product',),
        ),
    ]
