# Generated by Django 5.1 on 2024-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_cpucooler_fan_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpucooler',
            name='rgb',
            field=models.CharField(max_length=10),
        ),
    ]
