# Generated by Django 5.1 on 2024-09-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_cpucooler_rgb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casing',
            name='cooling_support',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='keyboards',
            name='rgb',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='rgb',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='modular',
            field=models.CharField(max_length=10),
        ),
    ]
