# Generated by Django 5.1 on 2024-09-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_casing_cooling_support_alter_keyboards_rgb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processors',
            name='base_clock',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='processors',
            name='boost_clock',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
