# Generated by Django 5.1 on 2024-09-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_processors_base_clock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processors',
            old_name='base_clock',
            new_name='clock_speed',
        ),
        migrations.RenameField(
            model_name='processors',
            old_name='cores',
            new_name='core',
        ),
        migrations.RenameField(
            model_name='processors',
            old_name='threads',
            new_name='thread',
        ),
    ]
