# Generated by Django 5.1 on 2024-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rename_base_clock_processors_clock_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
